### ISSUE TITLE
Provide basic docs

### ISSUE THREAD

**Issue by kristianmandrup** [bolav/fuse-npm#1]
Hi @bolav 
I've been interested in fuse for a while but been missing a few core features which you seem to cover in your repos, such as this one. Just wish you would provide some basic docs in the README for the usage scenarios (ie. why?), install and actual usage example (ie. how?)

I assume this repo would allow me to require npm modules from my `.ux` files?

Thanks :)

**Comment by bolav** [comment]
Yes. This module will transpile, "browserify" and copy the files you need and include them in the app-bundle. There are other ways to do that now that Fuse bundling has become easier, but I still think most npm modules need some massaging.

**Comment by jacksenechal** [comment]
Hi @bolav, I'm also interested in this but unsure from the existing README how to require the modules from a `.ux` file.
- where does one put the `fuse-npm` code relative to the project?
- what dir is the loadmodules.js script run from?
- what is the syntax for requiring it in a `.ux` file? `require('blah')`?
- do you need to require fuse-npm in your project? what's the mechanism that makes the node modules available to require?

Thanks!

**Comment by bolav** [comment]
I've tried to describe it now.

**Comment by bolav** [comment]
I've moved the functionality of this module to the Fuse Package Manager

https://github.com/bolav/fusepm
